
package ATM;

/**
 *
 * @author MN
 */
public class Bank_UI extends javax.swing.JFrame
{

 
    int WIDTH =850;
    int HEIGHT = 600;
    public Bank_UI()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BeneficiaryAccountGUI = new javax.swing.JFrame();
        ChooseTransactionGUI = new javax.swing.JFrame();
        btnViewBalance = new javax.swing.JButton();
        btnWithdraw = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnClose3 = new javax.swing.JButton();
        btnDeposit = new javax.swing.JButton();
        DepositGUI = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        txfAccountNumber = new javax.swing.JTextField();
        txfDepositAmount = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnCompleteDeposit = new javax.swing.JButton();
        btnClearAmount = new javax.swing.JButton();
        btnClearBeneficiary = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        FinalScreenGUI = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        btnClose4 = new javax.swing.JButton();
        LoginGUI = new javax.swing.JFrame();
        jpassword1 = new javax.swing.JPasswordField();
        label2 = new java.awt.Label();
        btnEnter = new java.awt.Button();
        btnClear = new java.awt.Button();
        lblPinIncorrect = new java.awt.Label();
        ViewBalanceGUI = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaViewBalance = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        btnGoBack = new java.awt.Button();
        btnClose = new java.awt.Button();
        WithdrawalGUI = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        btnMaxAvailable = new javax.swing.JButton();
        btnOwnAmount = new javax.swing.JButton();
        txfOwnAmount = new javax.swing.JTextField();
        btnWithdraw2 = new javax.swing.JButton();
        lblErrorMessage = new javax.swing.JLabel();
        ThankYouGUI = new javax.swing.JFrame();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnClose5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAccessAccount = new javax.swing.JButton();
        label1 = new java.awt.Label();

        BeneficiaryAccountGUI.setMinimumSize(new java.awt.Dimension(850, 600));

        javax.swing.GroupLayout BeneficiaryAccountGUILayout = new javax.swing.GroupLayout(BeneficiaryAccountGUI.getContentPane());
        BeneficiaryAccountGUI.getContentPane().setLayout(BeneficiaryAccountGUILayout);
        BeneficiaryAccountGUILayout.setHorizontalGroup(
            BeneficiaryAccountGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        BeneficiaryAccountGUILayout.setVerticalGroup(
            BeneficiaryAccountGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        ChooseTransactionGUI.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        ChooseTransactionGUI.setMinimumSize(new java.awt.Dimension(850, 600));
        ChooseTransactionGUI.setResizable(false);
        ChooseTransactionGUI.setSize(new java.awt.Dimension(850, 600));

        btnViewBalance.setText("View Balance");
        btnViewBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBalanceActionPerformed(evt);
            }
        });

        btnWithdraw.setText("Withdraw");
        btnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 1, 36)); // NOI18N
        jLabel2.setText("Choose an option");

        btnClose3.setText("Close");
        btnClose3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose3ActionPerformed(evt);
            }
        });

        btnDeposit.setText("Deposit");
        btnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ChooseTransactionGUILayout = new javax.swing.GroupLayout(ChooseTransactionGUI.getContentPane());
        ChooseTransactionGUI.getContentPane().setLayout(ChooseTransactionGUILayout);
        ChooseTransactionGUILayout.setHorizontalGroup(
            ChooseTransactionGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChooseTransactionGUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ChooseTransactionGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
                    .addGroup(ChooseTransactionGUILayout.createSequentialGroup()
                        .addGroup(ChooseTransactionGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnViewBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                            .addComponent(btnDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ChooseTransactionGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnWithdraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClose3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        ChooseTransactionGUILayout.setVerticalGroup(
            ChooseTransactionGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChooseTransactionGUILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 285, Short.MAX_VALUE)
                .addGroup(ChooseTransactionGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnWithdraw, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(btnDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ChooseTransactionGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnViewBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(btnClose3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        DepositGUI.setMinimumSize(new java.awt.Dimension(850, 600));

        jLabel7.setFont(new java.awt.Font("Maiandra GD", 2, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Deposit");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnCompleteDeposit.setText("Deposit");
        btnCompleteDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteDepositActionPerformed(evt);
            }
        });

        btnClearAmount.setText("Clear");
        btnClearAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearAmountActionPerformed(evt);
            }
        });

        btnClearBeneficiary.setText("Clear");
        btnClearBeneficiary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearBeneficiaryActionPerformed(evt);
            }
        });

        jLabel16.setText("Account");

        jLabel17.setText("Amount");

        javax.swing.GroupLayout DepositGUILayout = new javax.swing.GroupLayout(DepositGUI.getContentPane());
        DepositGUI.getContentPane().setLayout(DepositGUILayout);
        DepositGUILayout.setHorizontalGroup(
            DepositGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DepositGUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DepositGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(DepositGUILayout.createSequentialGroup()
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCompleteDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE))
                    .addGroup(DepositGUILayout.createSequentialGroup()
                        .addGroup(DepositGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DepositGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txfAccountNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                            .addComponent(txfDepositAmount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DepositGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClearAmount)
                            .addComponent(btnClearBeneficiary))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        DepositGUILayout.setVerticalGroup(
            DepositGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DepositGUILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(DepositGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfAccountNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(btnClearAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DepositGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfDepositAmount)
                    .addComponent(btnClearBeneficiary, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(200, 200, 200)
                .addGroup(DepositGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCompleteDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        FinalScreenGUI.setMinimumSize(new java.awt.Dimension(850, 600));

        jLabel8.setFont(new java.awt.Font("Maiandra GD", 3, 48)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Thank You for using Rich Bank");

        btnClose4.setText("Close");
        btnClose4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FinalScreenGUILayout = new javax.swing.GroupLayout(FinalScreenGUI.getContentPane());
        FinalScreenGUI.getContentPane().setLayout(FinalScreenGUILayout);
        FinalScreenGUILayout.setHorizontalGroup(
            FinalScreenGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FinalScreenGUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FinalScreenGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FinalScreenGUILayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClose4, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        FinalScreenGUILayout.setVerticalGroup(
            FinalScreenGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FinalScreenGUILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 372, Short.MAX_VALUE)
                .addComponent(btnClose4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        LoginGUI.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        LoginGUI.setMinimumSize(new java.awt.Dimension(850, 600));
        LoginGUI.setName("LoginWithPinGUI"); // NOI18N

        jpassword1.setColumns(4);
        jpassword1.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jpassword1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jpassword1.setToolTipText("Enter your 4 digit code");
        jpassword1.setFocusTraversalPolicyProvider(true);
        jpassword1.setVerifyInputWhenFocusTarget(false);
        jpassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpassword1ActionPerformed(evt);
            }
        });

        label2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Enter your pin code");

        btnEnter.setActionCommand("Enter");
        btnEnter.setBackground(new java.awt.Color(0, 255, 0));
        btnEnter.setForeground(new java.awt.Color(255, 255, 255));
        btnEnter.setLabel("Enter");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        btnClear.setActionCommand("Enter");
        btnClear.setBackground(new java.awt.Color(78, 80, 82));
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setLabel("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lblPinIncorrect.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout LoginGUILayout = new javax.swing.GroupLayout(LoginGUI.getContentPane());
        LoginGUI.getContentPane().setLayout(LoginGUILayout);
        LoginGUILayout.setHorizontalGroup(
            LoginGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginGUILayout.createSequentialGroup()
                .addGroup(LoginGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginGUILayout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginGUILayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(LoginGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpassword1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                            .addComponent(lblPinIncorrect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginGUILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        LoginGUILayout.setVerticalGroup(
            LoginGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginGUILayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPinIncorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jpassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addGroup(LoginGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEnter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ViewBalanceGUI.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        ViewBalanceGUI.setMinimumSize(new java.awt.Dimension(850, 600));

        txaViewBalance.setColumns(20);
        txaViewBalance.setRows(5);
        jScrollPane1.setViewportView(txaViewBalance);

        jLabel3.setFont(new java.awt.Font("Maiandra GD", 1, 36)); // NOI18N
        jLabel3.setText("View Balance");

        btnGoBack.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        btnGoBack.setLabel("Go Back");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        btnClose.setLabel("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ViewBalanceGUILayout = new javax.swing.GroupLayout(ViewBalanceGUI.getContentPane());
        ViewBalanceGUI.getContentPane().setLayout(ViewBalanceGUILayout);
        ViewBalanceGUILayout.setHorizontalGroup(
            ViewBalanceGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewBalanceGUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ViewBalanceGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ViewBalanceGUILayout.createSequentialGroup()
                        .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewBalanceGUILayout.createSequentialGroup()
                .addGap(0, 262, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(259, 259, 259))
        );
        ViewBalanceGUILayout.setVerticalGroup(
            ViewBalanceGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewBalanceGUILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(ViewBalanceGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGoBack, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        WithdrawalGUI.setMinimumSize(new java.awt.Dimension(850, 600));

        jLabel6.setFont(new java.awt.Font("Maiandra GD", 2, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Withdrawal");

        btnMaxAvailable.setText("Max Available");
        btnMaxAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaxAvailableActionPerformed(evt);
            }
        });

        btnOwnAmount.setText("Own Amount");
        btnOwnAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOwnAmountActionPerformed(evt);
            }
        });

        txfOwnAmount.setBackground(new java.awt.Color(255, 255, 255));
        txfOwnAmount.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N

        btnWithdraw2.setText("Withdraw");
        btnWithdraw2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdraw2ActionPerformed(evt);
            }
        });

        lblErrorMessage.setText("jLabel18");

        javax.swing.GroupLayout WithdrawalGUILayout = new javax.swing.GroupLayout(WithdrawalGUI.getContentPane());
        WithdrawalGUI.getContentPane().setLayout(WithdrawalGUILayout);
        WithdrawalGUILayout.setHorizontalGroup(
            WithdrawalGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WithdrawalGUILayout.createSequentialGroup()
                .addGroup(WithdrawalGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WithdrawalGUILayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(WithdrawalGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(WithdrawalGUILayout.createSequentialGroup()
                                .addComponent(btnMaxAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnWithdraw2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(WithdrawalGUILayout.createSequentialGroup()
                        .addGap(424, 424, 424)
                        .addComponent(btnOwnAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
                    .addGroup(WithdrawalGUILayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addGroup(WithdrawalGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txfOwnAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                            .addComponent(lblErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        WithdrawalGUILayout.setVerticalGroup(
            WithdrawalGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WithdrawalGUILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(lblErrorMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfOwnAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnOwnAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WithdrawalGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMaxAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnWithdraw2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ThankYouGUI.setFocusable(false);
        ThankYouGUI.setMinimumSize(new java.awt.Dimension(850, 600));

        jLabel12.setFont(new java.awt.Font("Maiandra GD", 0, 36)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Rich Bank");

        jLabel13.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Thank you for banking with us.");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("<html>\n<marque>\n<p>Thank you, Siyabonga, Baie Dankie, Rea Lotsha, Rea Leboga </p>\n</marque>\n</html>");

        jLabel15.setFont(new java.awt.Font("Maiandra GD", 2, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Where we take your money seriously");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnClose5.setText("Close");
        btnClose5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ThankYouGUILayout = new javax.swing.GroupLayout(ThankYouGUI.getContentPane());
        ThankYouGUI.getContentPane().setLayout(ThankYouGUILayout);
        ThankYouGUILayout.setHorizontalGroup(
            ThankYouGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThankYouGUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ThankYouGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThankYouGUILayout.createSequentialGroup()
                        .addGap(0, 414, Short.MAX_VALUE)
                        .addComponent(btnClose5, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ThankYouGUILayout.setVerticalGroup(
            ThankYouGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThankYouGUILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(btnClose5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ATM Home");
        setMaximumSize(new java.awt.Dimension(850, 600));
        setMinimumSize(new java.awt.Dimension(850, 600));
        setName("HomeGUI"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Rich Bank");

        btnAccessAccount.setText("Access Account");
        btnAccessAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccessAccountActionPerformed(evt);
            }
        });

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Maiandra GD", 2, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setName(""); // NOI18N
        label1.setText("Where we only care about your money");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 384, Short.MAX_VALUE)
                        .addComponent(btnAccessAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                .addComponent(btnAccessAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccessAccountActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAccessAccountActionPerformed
    {//GEN-HEADEREND:event_btnAccessAccountActionPerformed
        LoginGUI.setSize(850,600);
        LoginGUI.setVisible(true);
        Bank_UI.setDefaultLookAndFeelDecorated(rootPaneCheckingEnabled);
        
    }//GEN-LAST:event_btnAccessAccountActionPerformed

    private void jpassword1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jpassword1ActionPerformed
    {//GEN-HEADEREND:event_jpassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpassword1ActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCloseActionPerformed
    {//GEN-HEADEREND:event_btnCloseActionPerformed
        // Takes you back to home page
        
        ViewBalanceGUI.setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnClearActionPerformed
    {//GEN-HEADEREND:event_btnClearActionPerformed
        //Clears the password field
        jpassword1.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEnterActionPerformed
    {//GEN-HEADEREND:event_btnEnterActionPerformed
        //Moves to the next frame if password correct
        /*
        String testpin = "1234";
        String password = jpassword1.getText();
        
        if (password.equals(testpin))   {
            ChooseTransactionGUI.setSize(WIDTH, HEIGHT);
            ChooseTransactionGUI.setVisible(true);
            LoginGUI.setVisible(false);
        }
        if (jpassword1.getPassword().equals(testpin))   {
            ChooseTransactionGUI.setSize(WIDTH, HEIGHT);
            ChooseTransactionGUI.setVisible(true);
            LoginGUI.setVisible(false);
        }
        else    {
            lblPinIncorrect.setText("Pin Incorrect");
            jpassword1.setText("");
        }*/
        Login login = new Login();
        int pin = Integer.parseInt(jpassword1.getText());
        if(login.checkPin(pin)) {
            ChooseTransactionGUI.setSize(WIDTH, HEIGHT);
            ChooseTransactionGUI.setVisible(true);
            LoginGUI.setVisible(false);
            jpassword1.setText("");
        }
        else{
            lblPinIncorrect.setText("Pin Incorrect");
            jpassword1.setText("");
        
        }
        
    }//GEN-LAST:event_btnEnterActionPerformed

    private void btnViewBalanceActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnViewBalanceActionPerformed
    {//GEN-HEADEREND:event_btnViewBalanceActionPerformed
        Transactions trans = new Transactions();
        double bankBalance = trans.getBankBalance();
        txaViewBalance.setText("Your balance is:\n" + bankBalance);
        ViewBalanceGUI.setSize(WIDTH, HEIGHT);
        ViewBalanceGUI.setVisible(true);
        ChooseTransactionGUI.setVisible(false);
    }//GEN-LAST:event_btnViewBalanceActionPerformed

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnWithdrawActionPerformed
    {//GEN-HEADEREND:event_btnWithdrawActionPerformed
        txfOwnAmount.setVisible(false);
        lblErrorMessage.setVisible(false);
        WithdrawalGUI.setSize(WIDTH, HEIGHT);
        btnWithdraw2.setVisible(false);
        WithdrawalGUI.setVisible(true);
        ChooseTransactionGUI.setVisible(false);
    }//GEN-LAST:event_btnWithdrawActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGoBackActionPerformed
    {//GEN-HEADEREND:event_btnGoBackActionPerformed
        ViewBalanceGUI.setVisible(false);
        ChooseTransactionGUI.setVisible(true);
    }//GEN-LAST:event_btnGoBackActionPerformed

    private void btnClearAmountActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnClearAmountActionPerformed
    {//GEN-HEADEREND:event_btnClearAmountActionPerformed
        txfAccountNumber.setText("");
    }//GEN-LAST:event_btnClearAmountActionPerformed

    private void btnClearBeneficiaryActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnClearBeneficiaryActionPerformed
    {//GEN-HEADEREND:event_btnClearBeneficiaryActionPerformed
        txfDepositAmount.setText("");
    }//GEN-LAST:event_btnClearBeneficiaryActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelActionPerformed
    {//GEN-HEADEREND:event_btnCancelActionPerformed
        DepositGUI.setVisible(false);
        ChooseTransactionGUI.setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnClose3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnClose3ActionPerformed
    {//GEN-HEADEREND:event_btnClose3ActionPerformed
        ChooseTransactionGUI.setVisible(false);
    }//GEN-LAST:event_btnClose3ActionPerformed

    private void btnClose4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnClose4ActionPerformed
    {//GEN-HEADEREND:event_btnClose4ActionPerformed
        FinalScreenGUI.setVisible(false);
    }//GEN-LAST:event_btnClose4ActionPerformed

    private void btnCompleteDepositActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCompleteDepositActionPerformed
    {//GEN-HEADEREND:event_btnCompleteDepositActionPerformed
        /**
         * set  final frame visible
         * insert data into transaction table
         */
        int accountNumber = Integer.parseInt(txfAccountNumber.getText());
        double amount = Double.parseDouble(txfDepositAmount.getText());
        Transactions transactions = new Transactions();
        transactions.deposit(accountNumber, "Deposit", amount);
        
        DepositGUI.setVisible(false);
        ThankYouGUI.setSize(WIDTH, HEIGHT);
        ThankYouGUI.setVisible(true);

        
        
    }//GEN-LAST:event_btnCompleteDepositActionPerformed

    private void btnOwnAmountActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOwnAmountActionPerformed
    {//GEN-HEADEREND:event_btnOwnAmountActionPerformed
        btnOwnAmount.setVisible(false);
        txfOwnAmount.setVisible(true);
        btnWithdraw2.setVisible(true);
    }//GEN-LAST:event_btnOwnAmountActionPerformed

    private void btnWithdraw2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnWithdraw2ActionPerformed
    {//GEN-HEADEREND:event_btnWithdraw2ActionPerformed
        /**
         * set  final frame visible
         * insert data into transaction table
         */
        
        Double amount = Double.parseDouble(txfOwnAmount.getText());
        
        if (amount >= 50)   {
            Transactions transactions = new Transactions();
            transactions.withdrawal(123456789, "Withdrawal", amount);
        
            WithdrawalGUI.setVisible(false);
            ThankYouGUI.setSize(WIDTH, HEIGHT);
            ThankYouGUI.setVisible(true);
        
        }   
        else if (amount < 50)   {
            
            String msg = "cannot withdraw amount less than R50";
            lblErrorMessage.setText(msg);
            lblErrorMessage.setVisible(true);
            
        }
        Transactions transactions = new Transactions();
        transactions.withdrawal(123456789, "Withdrawal", amount);
        
        WithdrawalGUI.setVisible(false);
        ThankYouGUI.setSize(WIDTH, HEIGHT);
        ThankYouGUI.setVisible(true);
        
        
    }//GEN-LAST:event_btnWithdraw2ActionPerformed

    private void btnClose5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnClose5ActionPerformed
    {//GEN-HEADEREND:event_btnClose5ActionPerformed
        ThankYouGUI.setVisible(false);
    }//GEN-LAST:event_btnClose5ActionPerformed

    private void btnMaxAvailableActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnMaxAvailableActionPerformed
    {//GEN-HEADEREND:event_btnMaxAvailableActionPerformed
        Accounts acc = new Accounts();
        double bankBalance = acc.getBankBalance();
        Transactions trans = new Transactions();
        trans.withdrawal(123456789, "withdrawal", bankBalance);
        FinalScreenGUI.setSize(WIDTH, HEIGHT);
    }//GEN-LAST:event_btnMaxAvailableActionPerformed

    private void btnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositActionPerformed
        DepositGUI.setSize(WIDTH, HEIGHT);
        DepositGUI.setVisible(true);
    }//GEN-LAST:event_btnDepositActionPerformed

    
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bank_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bank_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bank_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bank_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Bank_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame BeneficiaryAccountGUI;
    private javax.swing.JFrame ChooseTransactionGUI;
    private javax.swing.JFrame DepositGUI;
    private javax.swing.JFrame FinalScreenGUI;
    private javax.swing.JFrame LoginGUI;
    private javax.swing.JFrame ThankYouGUI;
    private javax.swing.JFrame ViewBalanceGUI;
    private javax.swing.JFrame WithdrawalGUI;
    private javax.swing.JButton btnAccessAccount;
    private javax.swing.JButton btnCancel;
    private java.awt.Button btnClear;
    private javax.swing.JButton btnClearAmount;
    private javax.swing.JButton btnClearBeneficiary;
    private java.awt.Button btnClose;
    private javax.swing.JButton btnClose3;
    private javax.swing.JButton btnClose4;
    private javax.swing.JButton btnClose5;
    private javax.swing.JButton btnCompleteDeposit;
    private javax.swing.JButton btnDeposit;
    private java.awt.Button btnEnter;
    private java.awt.Button btnGoBack;
    private javax.swing.JButton btnMaxAvailable;
    private javax.swing.JButton btnOwnAmount;
    private javax.swing.JButton btnViewBalance;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JButton btnWithdraw2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField jpassword1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JLabel lblErrorMessage;
    private java.awt.Label lblPinIncorrect;
    private javax.swing.JTextArea txaViewBalance;
    private javax.swing.JTextField txfAccountNumber;
    private javax.swing.JTextField txfDepositAmount;
    private javax.swing.JTextField txfOwnAmount;
    // End of variables declaration//GEN-END:variables
}
